books/urls.py
from django.urls import path
from .views import BookListView, BookDetailView, GenreView, AddCommentView

app_name = 'books'
urlpatterns = [
    path('', BookListView.as_view(), name = 'books_list'),
    path('detail/<slug:slug>/', BookDetailView.as_view(), name = 'book_detail'),
    path('genre/<slug:slug>/', GenreView.as_view(), name = 'genre'),
    path('<slug:slug>/reviews/', AddCommentView.as_view(), name = 'reviews'),
]

config/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from .views import HomePageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(), name = 'home'),
    path('users/', include('users.urls')),
    path('books/', include('books.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

books/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils import timezone
from users.models import CustomUser

class Book(models.Model):
    languages = [
        ('english', 'english'),
        ('russian', 'russian'),
        ('uzbek', 'uzbek'),
        ('french', 'french')
    ]
    title = models.CharField(max_length=128)
    slug = models.SlugField(max_length=128, unique=True)
    description = models.TextField()
    image = models.ImageField(upload_to='media/images/books')
    isbn = models.CharField(max_length=20, blank=True)
    format = models.CharField(max_length=60)
    publish_time = models.DateTimeField(default=timezone.now)
    views = models.IntegerField(
        validators=[MinValueValidator(0)],
        blank=True
    )
    is_published = models.BooleanField(default=False)
    language = models.CharField(max_length=20, choices=languages, default='english')
    author = models.ManyToManyField('Author', related_name="book_author")
    genre = models.ManyToManyField('Genre')

    class Meta:
        verbose_name_plural = 'Books'

    def __str__(self):
        return self.title


class Author(models.Model):
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    email = models.EmailField(blank=True)
    bio = models.TextField(blank=True)
    genre = models.ManyToManyField('Genre', related_name='author_genre')
    website = models.CharField(max_length=128, blank=True)
    date_joined = models.DateTimeField(default=timezone.now)


    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"


class Genre(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=50, unique=True)

    def __str__(self):
        return self.name

class Comment(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    stars_given = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )
    text = models.TextField()

    def __str__(self):
        return self.user.username

books/forms.py
from django import forms
from .models import Comment

class AddCommentForm(forms.ModelForm):
    stars_given = forms.IntegerField(min_value=1, max_value=5)
    class Meta:
        model = Comment
        fields = ('text', 'stars_given')

books/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views import View
from django.core.paginator import Paginator

from .models import Book, Comment, Genre
from .forms import AddCommentForm

class BookListView(View):
    def get(self, request):
        search_book_title = request.GET.get("search_book", '')
        search_genre_book = request.GET.get("search_genre_books", '')

        if search_book_title:
            books = Book.objects.filter(title__icontains = search_book_title)
            paginator = Paginator(books, 4)
            page_num = request.GET.get('page', 1)
            page_obj = paginator.get_page(page_num)
        else:
            books = Book.objects.all().order_by('-id')
            paginator = Paginator(books, 4)
            page_num = request.GET.get('page', 1)
            page_obj = paginator.get_page(page_num)
        if search_genre_book:
            popular_books = Book.objects.filter(title__icontains = search_genre_book).order_by("-views")[:3]
            genres = Genre.objects.filter(name__icontains = search_genre_book)
        else:
            popular_books = Book.objects.all().order_by("-views")[:3]
            genres = Genre.objects.all()
        


        context = {
            'books':page_obj,
            'popular_books':popular_books,
            'genres':genres,
            'search_book_title':search_book_title,
            'search_genre_book':search_genre_book
        }
        return render(request, 'books/books_list.html', context)

class BookDetailView(View):
    def get(self, request, slug):
        try:
            form = AddCommentForm()
            book = Book.objects.get(slug = slug)
            context = {
                'book':book,
                'form':form
            }
            book.views += 1
            book.save()
            return render(request, 'books/book_detail.html', context)
        except ObjectDoesNotExist:
            return render(request, 'not_found.html')


class AddCommentView(LoginRequiredMixin, View):
    def post(self, request, slug):
        form = AddCommentForm(data=request.POST)
        book = Book.objects.get(slug = slug)
        if form.is_valid():
            Comment.objects.create(
                book = book,
                user = request.user,
                text = form.cleaned_data['text'],
                stars_given = form.cleaned_data['stars_given']
            )
            return redirect(reverse('books:book_detail', kwargs={'slug':book.slug}))
        else:
            return render(request, 'books/book_detail.html', {'form': form})


class GenreView(View):
    def get(self, request, slug):

        genre = Genre.objects.get(slug = slug)
        books = Book.objects.filter(genre = genre)
        genres = Genre.objects.all()
        context = {
            'genre':genre,
            'books':books,
            'genres':genres,
        }
        return render(request, 'books/genre.html', context)

books/templates/books/book_detail.html
{% extends 'base.html' %}
{% load static  %}
{% load widget_tweaks %}
{% block title %} {{ book.title }} {% endblock %}

{% block content %}
<div class="main-content container">

    <div class="page-content">
        <div class="container-fluid">

            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                        <h4 class="mb-sm-0 font-size-18">Book Detail</h4>


                    </div>
                </div>
            </div>
            <!-- end page title -->

            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-xl-6">
                                    <div class="product-detai-imgs">
                                        <div class="row">

                                            <div class="col-md-7 offset-md-1 col-sm-9 col-8">
                                                <div class="tab-content" id="v-pills-tabContent">
                                                    <div class="tab-pane fade show active" id="product-1"
                                                         role="tabpanel" aria-labelledby="product-1-tab">
                                                        <div>
                                                            <img src="{{ book.image.url }}" alt=""
                                                                 class="img-fluid mx-auto d-block">
                                                        </div>
                                                    </div>
                                                    <div class="tab-pane fade" id="product-2" role="tabpanel"
                                                         aria-labelledby="product-2-tab">
                                                        <div>
                                                            <img src="assets/images/product/img-8.png" alt=""
                                                                 class="img-fluid mx-auto d-block">
                                                        </div>
                                                    </div>
                                                    <div class="tab-pane fade" id="product-3" role="tabpanel"
                                                         aria-labelledby="product-3-tab">
                                                        <div>
                                                            <img src="assets/images/product/img-7.png" alt=""
                                                                 class="img-fluid mx-auto d-block">
                                                        </div>
                                                    </div>
                                                    <div class="tab-pane fade" id="product-4" role="tabpanel"
                                                         aria-labelledby="product-4-tab">
                                                        <div>
                                                            <img src="assets/images/product/img-8.png" alt=""
                                                                 class="img-fluid mx-auto d-block">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-xl-6">
                                    <div class="mt-4 mt-xl-3">
                                        <a href="{% url 'books:books_list' %}" class="text-primary">Books List</a>
                                        <h4 class="mt-1 mb-3">{{ book.title }}</h4>

                                        <p class="text-muted float-start me-3">
                                            <span class="bx bxs-star text-warning"></span>
                                            <span class="bx bxs-star text-warning"></span>
                                            <span class="bx bxs-star text-warning"></span>
                                            <span class="bx bxs-star text-warning"></span>
                                            <span class="bx bxs-star"></span>
                                        </p>
                                        <p class="text-muted mb-4">( 152 Customers Review )</p>

                                        {% for author in book.author.all %}
                                        {% if forloop.last %}
                                        <span class="text-capitalize fs-3 mb-4">{{ author.get_full_name }}</span>
                                        {% else %}
                                        <span class="mb-4">{{ author.get_full_name }}</span>
                                        {% endif %}
                                        {% endfor %}
                                        <br> <br>

                                        <p class="text-muted mb-4">{{ book.description }}</p>


                                    </div>
                                </div>
                            </div>
                            <!-- end row -->

                            <div class="mt-5">
                                <h5 class="mb-3">Features :</h5>

                                <div class="table-responsive">
                                    <table class="table mb-0 table-bordered">
                                        <tbody>
                                        <tr>
                                            <th scope="row" style="width: 400px;">Genre</th>
                                            <td>
                                                {% for g in book.genre.all %}
                                                {% if forloop.last %}
                                                {{ g.name }}
                                                {% else %}
                                                {{ g.name }},
                                                {% endif %}
                                                {% endfor %}
                                            </td>
                                        </tr>
                                        <tr>
                                            <th scope="row">Format</th>
                                            <td>{{ book.format }}</td>
                                        </tr>
                                        <tr>
                                            <th scope="row">Language</th>
                                            <td>{{ book.language }}</td>
                                        </tr>
                                        {% if book.isbn %}
                                        <tr>
                                            <th scope="row">Isbn</th>
                                            <td>{{ book.isbn }}</td>
                                        </tr>
                                        {% endif %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <!-- end Specifications -->


                            <div class="mt-5">
                                <div class="mt-4">
                                                                <h5 class="font-size-16 mb-3">Leave a Message</h5>

                                                                <form method="post" action="{% url 'books:reviews' book.slug %}">
                                                                    {% csrf_token %}
                                                                    <div class="row">
                                                                        <div class="col-md-6">
                                                                            <div class="mb-3">
                                                                                <label for="stars_given" class="form-label">Stars</label>
<!--                                                                                <input type="number" class="form-control" id="stars_given">-->
                                                                                {% render_field form.stars_given class+="form-control" id="stars_given" type="number" %}
                                                                            </div>
                                                                        </div>

                                                                    </div>
                                                                    <div class="row">
                                                                        <div class="col-md-6">
                                                                            <div class="mb-3">
                                                                            <label for="commentmessage-input" class="form-label">Message</label>
    <!--                                                                        <textarea class="form-control" id="commentmessage-input" placeholder="Your message..." rows="3"></textarea>-->
                                                                            {% render_field form.text class+="form-control" id="commentmessage-input" type="number" rows="3" placeholder="Your message..." %}
                                                                                <div class="text-end mt-3">
                                                                                    <button type="submit" class="btn btn-success w-sm">Submit</button>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                    </div>




                                                                </form>
                                                            </div>
                                {% if book.comment_set.all %}

                                <h5 class="font-size-15"><i class="bx bx-message-dots text-muted align-middle me-1"></i>
                                    Comments :</h5>

                                <div>
                                    {% for comment in book.comment_set.all %}
                                    <div class="d-flex py-3">
                                        <div class="flex-shrink-0 me-3">
                                            <div class="avatar-xs">
                                                <div class="flex-shrink-0 me-3">
                                                    <img src="{{ comment.user.picture.url }}"
                                                         class="avatar-xs rounded-circle" alt="img"/>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="flex-grow-1">
                                            <h5 class="font-size-14 mb-1">{{ comment.user.get_full_name }} <small
                                                    class="text-muted float-end">{{ comment.created_at }}</small></h5>
                                            <p class="text-muted">{{ comment.text }}</p>
                                        </div>

                                    </div>
                                    {% endfor %}
                                </div>
                                {% endif %}
                            </div>


                        </div>
                    </div>
                    <!-- end card -->
                </div>
            </div>
            <!-- end row -->


            <!-- end row -->

        </div> <!-- container-fluid -->
    </div>
    <!-- End Page-content -->

</div>
{% endblock %}